resolver: lts-14.24

packages:
- .

extra-deps:
# - iwlib-0.1.0
- xmobar-0.32@sha256:f2cf80a8b524642ff28b8a821ebcba6908238080eb2df9ca09f02f643c92a83c,10784

flags:
  xmobar:
    with_dbus: true
    with_threaded: true
    with_utf8: true
    with_xft: true
    with_mpd: false
    with_mpris: false
    with_inotify: false
    with_iwlib: false
    with_alsa: true
    with_datezone: true
    with_xpm: false
    with_uvmeter: false
    with_weather: false
